# Generated by Django 4.2.11 on 2024-08-07 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterparties', '0004_alter_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityMeteringPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Место расположение точки учета')),
                ('power_supply', models.CharField(max_length=255, verbose_name='Источник питания')),
                ('tariff', models.CharField(choices=[('urban_population_tariff', 'Тариф для городского населения с однотирфным прибором учета'), ('rural_population_tariff', 'Тариф для сельского населения с однотирфным прибором учета'), ('low_voltage_tariff', 'Тариф для потребителей с уровнем напряжения НН, рассчитывающихся по I ценовой категории'), ('medium_voltage_tariff_1', 'Тариф для потребителей с уровнем напряжения СН-I, рассчитывающихся по I ценовой категории'), ('medium_voltage_tariff_2', 'Тариф для потребителей с уровнем напряжения СН-II, рассчитывающихся по I ценовой категории'), ('high_voltage_tariff', 'Тариф для потребителей с уровнем напряжения ВН, рассчитывающихся по I ценовой категории'), ('tariff-free', 'Бездоговорное потребление')], default='tariff-free', max_length=200, verbose_name='Тариф')),
                ('margin', models.CharField(choices=[('first_level_margin', 'Первый уровень наценки к тарифу'), ('second_level_margin', 'Второй уровень наценки к тарифу'), ('third_level_margin', 'Третий уровень наценки к тарифу'), ('fourth_level_margin', 'Четвёртый уровень наценки к тарифу'), ('fifth_level_margin', 'Пятый уровень наценки к тарифу'), ('margin-free', 'Без наценки к тарифу')], default='margin-free', max_length=200, verbose_name='Наценка')),
                ('electricity_loss_in_lines', models.FloatField(default=0, verbose_name='Процент потерь электроэнергии в линиях')),
                ('electricity_loss_in_transformers', models.FloatField(default=0, verbose_name='Постоянные потери электроэнергии в трансформаторах')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='counterparties.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Точка учета электроэнергии',
                'verbose_name_plural': 'Точки учета электроэнергии',
            },
        ),
    ]
