# Generated by Django 4.2.11 on 2024-08-07 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricitymeteringpoint',
            name='electricity_loss_in_lines',
        ),
        migrations.RemoveField(
            model_name='electricitymeteringpoint',
            name='electricity_loss_in_transformers',
        ),
        migrations.RemoveField(
            model_name='electricitymeteringpoint',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='electricitymeteringpoint',
            name='tariff',
        ),
    ]
