# Generated by Django 4.2.11 on 2024-08-13 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_accounting', '0002_remove_electricitymeteringpoint_electricity_loss_in_lines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitymeteringpoint',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Наименование точки учёта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electricitymeteringpoint',
            name='type_of_accounting',
            field=models.CharField(choices=[('Technical accounting', 'Технический учёт'), ('Calculation accounting', 'Расчётный учёт')], default='Calculation accounting', max_length=255, verbose_name='Тип учёта'),
        ),
        migrations.CreateModel(
            name='ElectricityMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('mark', models.CharField(blank=True, max_length=255, verbose_name='Марка счётчика электроэнергии')),
                ('number', models.CharField(blank=True, max_length=255, verbose_name='Заводской номер счётчика электроэнергии')),
                ('installation_date', models.DateField(verbose_name='Дата установки')),
                ('date_of_next_verification', models.DateField(verbose_name='Дата следующей поверки')),
                ('point', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='electricity_accounting.electricitymeteringpoint', verbose_name='Точка учёта электроэнергии')),
            ],
            options={
                'verbose_name': 'Счётчик электроэнергии',
                'verbose_name_plural': 'Счётчики электроэнергии',
            },
        ),
        migrations.CreateModel(
            name='CurrentTransformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('mark', models.CharField(blank=True, max_length=255, verbose_name='Тип трансформатора тока')),
                ('number', models.CharField(blank=True, max_length=255, verbose_name='Заводской номер трансформатора тока')),
                ('installation_date', models.DateField(verbose_name='Дата установки')),
                ('date_of_next_verification', models.DateField(verbose_name='Дата следующей поверки')),
                ('point', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transformers', to='electricity_accounting.electricitymeteringpoint', verbose_name='Точка учёта электроэнергии')),
            ],
            options={
                'verbose_name': 'Трансформатор тока',
                'verbose_name_plural': 'Трансформаторы тока',
            },
        ),
    ]
