# Generated by Django 4.2.11 on 2024-08-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_accounting', '0003_electricitymeteringpoint_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricitymeteringpoint',
            name='type_of_accounting',
            field=models.CharField(choices=[('Calculation accounting', 'Расчётный учёт'), ('Control accounting', 'Контрольный учёт'), ('Mutual settlement accounting', 'Взаиморасчетный учёт'), ('Transit accounting', 'Транзитный учёт')], default='Calculation accounting', help_text='Прибор учёта может быть расчетным, контрольным, взаиморасчетным, транзитным. Для взаиморасчетных приборов указывается из-под какого (№ счетчика) производится расчет', max_length=255, verbose_name='Тип учёта'),
        ),
    ]
