# Generated by Django 4.2.11 on 2024-08-16 01:22

from django.db import migrations, models
import django.db.models.deletion
import electricity_accounting.models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0006_alter_counterparty_registration_reason_code'),
        ('electricity_accounting', '0004_alter_electricitymeteringpoint_type_of_accounting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricitymeter',
            options={'ordering': ('-installation_date',), 'verbose_name': 'Счётчик электроэнергии', 'verbose_name_plural': 'Счётчики электроэнергии'},
        ),
        migrations.AlterModelOptions(
            name='electricitymeteringpoint',
            options={'ordering': ('contract',), 'verbose_name': 'Точка учета электроэнергии', 'verbose_name_plural': 'Точки учета электроэнергии'},
        ),
        migrations.AddField(
            model_name='currenttransformer',
            name='photo',
            field=models.ImageField(blank=True, upload_to=electricity_accounting.models.point_directory_path, verbose_name='Фотография трансформатора тока'),
        ),
        migrations.AddField(
            model_name='electricitymeter',
            name='photo',
            field=models.ImageField(blank=True, upload_to=electricity_accounting.models.point_directory_path, verbose_name='Фотография счётчика'),
        ),
        migrations.AlterField(
            model_name='electricitymeteringpoint',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points', to='counterparties.contract', verbose_name='Договор'),
        ),
    ]
