# Generated by Django 4.2.11 on 2024-08-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_accounting', '0005_alter_electricitymeter_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Дата внесения расценок')),
                ('begin_tariff_period', models.DateField(verbose_name='Начало периода действия тарифов')),
                ('end_tariff_period', models.DateField(verbose_name='Окончание периода действия тарифов')),
                ('urban_population_tariff', models.FloatField(verbose_name='Тариф для городского населения с однотирфным прибором учета')),
                ('rural_population_tariff', models.FloatField(verbose_name='Тариф для сельского населения с однотирфным прибором учета')),
                ('low_voltage_tariff', models.FloatField(verbose_name='Тариф для потребителей с уровнем напряжения НН, рассчитывающихся по I ценовой категории')),
                ('medium_voltage_tariff_1', models.FloatField(verbose_name='Тариф для потребителей с уровнем напряжения СН-I, рассчитывающихся по I ценовой категории')),
                ('medium_voltage_tariff_2', models.FloatField(verbose_name='Тариф для потребителей с уровнем напряжения СН-II, рассчитывающихся по I ценовой категории')),
                ('high_voltage_tariff', models.FloatField(verbose_name='Тариф для потребителей с уровнем напряжения ВН, рассчитывающихся по I ценовой категории')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ('-end_tariff_period',),
            },
        ),
        migrations.AlterField(
            model_name='electricitymeter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='electricitymeter',
            name='photo',
            field=models.ImageField(blank=True, upload_to='contracts/', verbose_name='Фотография счётчика'),
        ),
    ]
