# Generated by Django 4.2.11 on 2024-08-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_accounting', '0006_tariff_alter_electricitymeter_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='rural_population_tariff',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='urban_population_tariff',
        ),
        migrations.AddField(
            model_name='tariff',
            name='rural_tariff_1',
            field=models.FloatField(default=1, help_text='Тариф для сельского населения с однотирфным прибором учета.\n                     Для первого диапазона объемов потребления (до 10980 кВт*ч)', verbose_name='Сельское 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='rural_tariff_2',
            field=models.FloatField(default=1, help_text='Тариф для сельского населения с однотирфным прибором учета.\n                     Для второго диапазона объемов потребления (от 10980 – 14640 кВт*ч)', verbose_name='Сельское 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='rural_tariff_3',
            field=models.FloatField(default=1, help_text='Тариф для сельского населения с однотирфным прибором учета.\n                     Для третьего диапазона объемов потребления (свыше 14640 кВт*ч)', verbose_name='Сельское 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='urban_tariff_1',
            field=models.FloatField(default=1, help_text='Тариф для городского населения с однотирфным прибором учета.\n                     Для первого диапазона объемов потребления (до 10980 кВт*ч)', verbose_name='Городское 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='urban_tariff_2',
            field=models.FloatField(default=1, help_text='Тариф для городского населения с однотирфным прибором учета.\n                     Для второго диапазона объемов потребления (от 10980 – 14640 кВт*ч)', verbose_name='Городское 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='urban_tariff_3',
            field=models.FloatField(default=1, help_text='Тариф для городского населения с однотирфным прибором учета.\n                     Для третьего диапазона объемов потребления (свыше 14640 кВт*ч)', verbose_name='Городское 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tariff',
            name='begin_tariff_period',
            field=models.DateField(help_text='Начало периода действия тарифов', verbose_name='Начало периода'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='end_tariff_period',
            field=models.DateField(help_text='Окончание периода действия тарифов', verbose_name='Окончание периода'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='high_voltage_tariff',
            field=models.FloatField(help_text='Тариф для потребителей с уровнем напряжения ВН,\n                     рассчитывающихся по I ценовой категории', verbose_name='ВН'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='low_voltage_tariff',
            field=models.FloatField(help_text='Тариф для потребителей с уровнем напряжения НН,\n                     рассчитывающихся по I ценовой категории', verbose_name='НН'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='medium_voltage_tariff_1',
            field=models.FloatField(help_text='Тариф для потребителей с уровнем напряжения СН-I,\n                     рассчитывающихся по I ценовой категории', verbose_name='СН-I'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='medium_voltage_tariff_2',
            field=models.FloatField(help_text='Тариф для потребителей с уровнем напряжения СН-II,\n                     рассчитывающихся по I ценовой категории', verbose_name='СН-II'),
        ),
    ]
