# Generated by Django 4.2.11 on 2024-09-02 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_accounting', '0008_electricitymeteringpoint_constant_losses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(verbose_name='Дата снятия показаний')),
                ('readings', models.FloatField(verbose_name='Показания счётчика электрической энергии')),
                ('previous_entry_date', models.DateField(verbose_name='Дата снятия предыдущих показаний')),
                ('previous_readings', models.FloatField(verbose_name='Предыдущие показания счётчика электрической энергии')),
                ('difference_readings', models.FloatField(verbose_name='Разность показаний')),
                ('transformation_coefficient', models.PositiveIntegerField(verbose_name='Коэффициент транформации')),
                ('amount', models.FloatField(verbose_name='Количество кВтч')),
                ('deductible_amount', models.FloatField(verbose_name='Вычитаемое количество кВтч')),
                ('losses', models.PositiveIntegerField(verbose_name='Процент потерь на линиях')),
                ('constant_losses', models.PositiveIntegerField(verbose_name='Постоянныен потери трансформатора, кВтч/месяц')),
                ('result_amount', models.FloatField(verbose_name='Результат кВтч')),
                ('tariff', models.FloatField(verbose_name='тариф')),
                ('margin', models.FloatField(help_text='Добавочная стоимость, руб./кВтч', verbose_name='Наценка')),
                ('accrued', models.FloatField(verbose_name='Начислено')),
                ('accrued_NDS', models.FloatField(verbose_name='Начислено с НДС')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity_accounting.electricitymeter')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity_accounting.electricitymeteringpoint')),
            ],
        ),
        migrations.DeleteModel(
            name='Indications',
        ),
    ]
