# Generated by Django 4.2.11 on 2024-09-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_accounting', '0009_calculation_delete_indications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculation',
            options={'ordering': ('-entry_date',), 'verbose_name': 'Показания', 'verbose_name_plural': 'Показания'},
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='tariff',
        ),
        migrations.AddField(
            model_name='calculation',
            name='tariff1',
            field=models.FloatField(default=0, verbose_name='Тариф для первого диапазона объёмов потребления (до 10980 кВт*ч)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculation',
            name='tariff2',
            field=models.FloatField(default=0, verbose_name='Тариф для второго диапазона объёмов потребления (от 10980 – 14640 кВт*ч)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculation',
            name='tariff3',
            field=models.FloatField(default=0, verbose_name='Тариф тля третьего диапазона объёмов потребления (свыше 14640 кВт*ч)'),
            preserve_default=False,
        ),
    ]
