# Generated by Django 4.2.11 on 2024-09-12 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_accounting', '0010_alter_calculation_options_remove_calculation_tariff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeductionAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_point', to='electricity_accounting.electricitymeteringpoint')),
                ('lower_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lower_point', to='electricity_accounting.electricitymeteringpoint')),
            ],
            options={
                'verbose_name': 'Вычет',
                'verbose_name_plural': 'Вычеты',
            },
        ),
        migrations.AddConstraint(
            model_name='deductionamount',
            constraint=models.UniqueConstraint(fields=('head_point', 'lower_point'), name='unique_deduction'),
        ),
    ]
