# Generated by Django 4.2.11 on 2024-10-01 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_accounting', '0011_deductionamount_deductionamount_unique_deduction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeductionAmount',
            new_name='InterconnectedPoints',
        ),
    ]
