# Generated by Django 4.2.11 on 2024-10-07 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_accounting', '0012_rename_deductionamount_interconnectedpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='electricity_accounting.electricitymeteringpoint'),
        ),
        migrations.AlterField(
            model_name='interconnectedpoints',
            name='head_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_point', to='electricity_accounting.electricitymeteringpoint', verbose_name='Головной учёт'),
        ),
        migrations.AlterField(
            model_name='interconnectedpoints',
            name='lower_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lower_point', to='electricity_accounting.electricitymeteringpoint', verbose_name='Нижестоящий учёт'),
        ),
    ]
