# Generated by Django 4.2.11 on 2024-10-09 07:23

from django.db import migrations, models
import django.db.models.deletion
import electricity_accounting.models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_accounting', '0013_alter_calculation_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interconnectedpoints',
            name='lower_point',
            field=models.ForeignKey(help_text=('Объём потребленной электроэнрегии нижестоящей точки учета', 'вычитается из объёма потреблённой электроэнергии', 'вышестоящей точки учёта.'), on_delete=django.db.models.deletion.CASCADE, related_name='lower_point', to='electricity_accounting.electricitymeteringpoint', verbose_name='Нижестоящий учёт'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion_date', models.DateField(blank=True, null=True, verbose_name='Дата подписания документа')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование документа')),
                ('file', models.FileField(upload_to=electricity_accounting.models.point_directory_path)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='electricity_accounting.electricitymeteringpoint')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ('conclusion_date',),
            },
        ),
    ]
