# Generated by Django 4.2.11 on 2024-10-16 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_accounting', '0014_alter_interconnectedpoints_lower_point_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interconnectedpoints',
            options={'verbose_name': 'Взаимосвязь', 'verbose_name_plural': 'Взаимосвязи'},
        ),
    ]
