# Generated by Django 4.2.11 on 2024-04-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=255, verbose_name='Сокращенное наименование')),
                ('address', models.CharField(max_length=200, verbose_name='Юридический адрес')),
                ('phone_number', models.CharField(blank=True, max_length=16, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронный адрес')),
                ('main_state_registration_number', models.PositiveBigIntegerField(db_column='OGRN', unique=True, verbose_name='ОГРН')),
                ('registration_reason_code', models.PositiveIntegerField(db_column='KPP', verbose_name='КПП')),
                ('tax_identification_number', models.PositiveBigIntegerField(db_column='INN', unique=True, verbose_name='ИНН')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='Должность руководителя')),
                ('person_full_name', models.CharField(max_length=200, verbose_name='Фамилия, имя и отчество (если есть)')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ('full_name',),
            },
        ),
    ]
