# Generated by Django 4.2.11 on 2024-07-31 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0002_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('conclusion_date',), 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AddField(
            model_name='document',
            name='conclusion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подписания документа'),
        ),
    ]
