# Generated by Django 4.2.11 on 2024-11-18 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='agreement_type',
            field=models.CharField(choices=[('Contract', 'Контракт'), ('Dogovor', 'Договор')], default='Dogovor', help_text='Выбирите тип соглашения из предложенных вариантов.', max_length=255, verbose_name='Тип соглашения'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='counterparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='counterparties.counterparty', verbose_name='Контрагент'),
        ),
    ]
