# Generated by Django 4.2.11 on 2024-08-07 02:11

import counterparties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0003_alter_document_options_document_conclusion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=counterparties.models.contract_directory_path),
        ),
    ]
