# Generated by Django 4.2.11 on 2024-07-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0003_alter_contract_counterparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='actual_cost',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Фактическая стоимость выполненных работ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='сompletion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения работ'),
        ),
    ]
