# Generated by Django 4.2.11 on 2024-08-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0004_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена договора'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='main_state_registration_number',
            field=models.PositiveBigIntegerField(db_column='OGRN', help_text='ОГРН - основной государственный регистрационный номер.\n                     ОГРН состоит из 13 арабских цифр.\n                     ОГРН индивидуального предпринимателя (ОГРНИП) состоит\n                     из 15 арабских цифр.', unique=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='registration_reason_code',
            field=models.PositiveIntegerField(blank=True, db_column='KPP', help_text='КПП - код причины постановки на учёт.\n                     КПП юридического лица состоит из 9 арабских цифр.\n                     Индивидуальные предприниматели на имеют КПП\n                     (приказ ФНС №ММВ-7-6/435).', null=True, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='tax_identification_number',
            field=models.PositiveBigIntegerField(db_column='INN', help_text='ИНН — идентификационный номер налогоплательщика. \n                     ИНН физического лица состоит из 12 арабских цифр. \n                     ИНН юридического лица состоит из 10 арабских цифр.', unique=True, verbose_name='ИНН'),
        ),
    ]
