# Generated by Django 4.2.11 on 2024-08-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0005_alter_contract_contract_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='registration_reason_code',
            field=models.PositiveIntegerField(blank=True, db_column='KPP', help_text='КПП - код причины постановки на учёт.\n                     КПП юридического лица состоит из 9 арабских цифр.\n                     Индивидуальные предприниматели не имеют КПП\n                     (приказ ФНС №ММВ-7-6/435).', null=True, verbose_name='КПП'),
        ),
    ]
