# Generated by Django 4.2.11 on 2024-10-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
