from django.urls import path

from . import views
from counterparties import views as counterparties_views


app_name = 'accounting'

urlpatterns = [
    path(
        'point_detail/<int:point_id>/meter_create/',
        views.meter_create,
        name='meter_create',        
    ),
    path(
        'point_detail/<int:point_id>/meter/<int:meter_id>/delete/',
        views.meter_delete,
        name='meter_delete',        
    ),
    path(
        'point_detail/<int:point_id>/meter/<int:meter_id>/edit/',
        views.meter_edit,
        name='meter_edit',        
    ),
     path(
        'point_detail/<int:point_id>/transformer_create/',
        views.transformer_create,
        name='transformer_create',        
    ),
    path(
        'point_detail/<int:point_id>/transformer/<int:transformer_id>/delete/',
        views.transformer_delete,
        name='transformer_delete',        
    ),
    path(
        'point_detail/<int:point_id>/transformer/<int:transformer_id>/edit/',
        views.transformer_edit,
        name='transformer_edit',        
    ),
    path(
        'counterparties/contract_detail/<int:contract_id>/point_create/',
        views.point_create,
        name='point_create',
    ),
    path(
        'point_detail/<int:point_id>/',
        views.point_detail,
        name='point_detail',
    ),
    path(
        'point_detail/<int:point_id>/delete/',
        views.point_delete,
        name='point_delete',
    ),
    path(
        'point_detail/<int:point_id>/edit/',
        views.point_edit,
        name='point_edit',
    ),
    path(
        'points_list/',
        views.points_list,
        name='points_list',
    ),
    path(
        'tariff_create/',
        views.tariff_create,
        name='tariff_create',
    ),
    path(
        'tariffs/<int:tariff_id>/delete/',
        views.tariff_delete,
        name='tariff_delete',
    ),
    path(
        'tariffs/<int:tariff_id>/edit/',
        views.tariff_edit,
        name='tariff_edit',
    ),
    path(
        'tariffs_list/',
        views.tariffs_list,
        name='tariffs_list',
    ),
    path(
        'point_detail/<int:point_id>/calculations/add_calculation/',
        views.add_calculation,
        name='add_calculation',
    ),
    path(
        'point_detail/<int:point_id>/calculations/<int:calculation_id>/delete/',
        views.del_calculation,
        name='del_calculation',
    ),
    path(
        'point_detail/<int:point_id>/calculations/<int:calculation_id>/edit/',
        views.calculation_edit,
        name='calculation_edit',
    ),
    path(
        'point_detail/<int:point_id>/calculations/<int:calculation_id>/update/',
        views.calculation_tariff_update,
        name='calculation_tariff_update',
    ),
    path(
        'point_detail/<int:point_id>/calculations/<int:calculation_id>/download_xlsx_document/',
        views.download_xlsx_document,
        name='download_xlsx_document',
    ),
    path(
        'point_detail/<int:point_id>/interconnections/create/',
        views.interconnection_create,
        name='interconnection_create',
    ),
    path(
        'point_detail/<int:point_id>/interconnections/<int:interconnection_id>/delete/',
        views.interconnection_delete,
        name='interconnection_delete',
    ),
    path(
        'point_detail/<int:point_id>/document/create/',
        views.document_add,
        name='document_add',
    ),
    path(
        'point_detail/<int:point_id>/document/<int:document_id>/delete/',
        views.document_delete,
        name='document_delete',
    ),
    path(
        'point_detail/<int:point_id>/comments/create/',
        counterparties_views.comment_create,
        name='comment_point_create',
    ),
    path(
        'point_detail/<int:point_id>/comments/<int:comment_id>/delete/',
        counterparties_views.comment_delete,
        name='comment_point_delete',
    ),
    path(
        'point_detail/<int:point_id>/comments/<int:comment_id>/edit/',
        counterparties_views.comment_edit,
        name='comment_point_edit',
    ),
    path(
        'static/<int:year>/',
        views.cumulative_statement_of_electricity_consumption,
        name='cumulative_statement_of_electricity_consumption',
    ),
    path(
        'static/<int:year>/download_xlsx_document_yearly_consumptions/',
        views.download_xlsx_document_yearly_consumptions,
        name='download_xlsx_document_yearly_consumptions',
    ),
]
