# Generated by Django 4.2.11 on 2024-07-10 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Сотрудник организации', 'verbose_name_plural': 'Сотрудники организации'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=254, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/', verbose_name='Фотография сотрудника'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='post',
            field=models.CharField(default=1, max_length=254, verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=254, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=254, verbose_name='Фамилия'),
        ),
    ]
