# Generated by Django 4.2.11 on 2024-10-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='letter_of_attorney',
            field=models.CharField(blank=True, help_text='Доверенность на право подписания документов от лица организации', max_length=254, verbose_name='Доверенность'),
        ),
    ]
