# Generated by Django 4.2.11 on 2024-11-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=255, verbose_name='Сокращенное наименование')),
                ('address', models.CharField(max_length=200, verbose_name='Юридический адрес')),
                ('phone_number', models.CharField(blank=True, max_length=16, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронный адрес')),
                ('main_state_registration_number', models.PositiveBigIntegerField(db_column='OGRN', help_text='ОГРН - основной государственный регистрационный номер.\n                     ОГРН состоит из 13 арабских цифр.\n                     ОГРН индивидуального предпринимателя (ОГРНИП) состоит\n                     из 15 арабских цифр.', unique=True, verbose_name='ОГРН')),
                ('tax_identification_number', models.PositiveBigIntegerField(db_column='INN', help_text='ИНН — идентификационный номер налогоплательщика. \n                     ИНН физического лица состоит из 12 арабских цифр. \n                     ИНН юридического лица состоит из 10 арабских цифр.', unique=True, verbose_name='ИНН')),
                ('registration_reason_code', models.PositiveIntegerField(blank=True, db_column='KPP', help_text='КПП - код причины постановки на учёт.\n                     КПП юридического лица состоит из 9 арабских цифр.\n                     Индивидуальные предприниматели не имеют КПП\n                     (приказ ФНС №ММВ-7-6/435).', null=True, verbose_name='КПП')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='Должность руководителя')),
                ('person_full_name', models.CharField(max_length=200, verbose_name='Фамилия, имя и отчество (если есть)')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
    ]
